PWD!=pwd | sed 's/^\/mnt//'
DOCKER=docker run -it -v "$(PWD):/srv" -w=/srv nowox/latex:1.1

VSDXs=$(shell ls assets/visio/*.vsdx)
SVGS=$(patsubst assets/visio/%.vsdx,assets/figures/%.svg,$(VSDXs))
PDFS=$(patsubst assets/figures/%.svg,assets/figures/%.pdf,$(SVGS))

all: revision.tex
	$(DOCKER) latexmk -pdf -xelatex main.tex

clean:
	$(DOCKER) latexmk -C

%.pdf: %.svg
	rsvg-convert -f pdf -o $@ $^

revision.tex:
	echo "% Autogenerated, do not edit" > $@
	echo "\\\\newcommand{\\\\revisiondate}{`git log -1 --format=\"%ad\" --date=short`}" >> $@
	echo "\\\\newcommand{\\\\revision}{`git describe`}" >> $@

assets/figures/%.svg: assets/visio/%.vsdx
	./visio2svg.sh $< $@

assets: $(PDFS)

.PHONY: all clean assets